#! /bin/sh


# Startups
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore &
picom -f &


# focus with pointer
bspc config focus_follows_pointer true

# Monitor setup
bspc config -m eDP-1 top_padding 48



# border colors basic
bspc config focused_border_color '#e1b2d4'
bspc config normal_border_color '#1A1826'


bspc monitor -d 1 2 3 4 5 
# window gap and width
bspc config border_width         3
bspc config window_gap           10

# Defaults
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^2' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Galculator state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
